language: python
python:
  - "3.6"
# command to install dependencies
addons:
  apt:
    packages:
      - build-essential
install:
  - pip install --quiet torch torchvision
  - pip install --quiet -r requirements.txt
# command to run tests
script:
  - pytest --cov=speech_generation speech_generation/tests
after_success:
  - coveralls