language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install torch torchvision
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest speech_generation/tests