data: 'train-data'
test-data: 'test-data'
hidden_size: 200
batch_size: 1
embed_dim: 300
sample_iter: 10
num_convolutional_features: 2
max_length: 50
critic_iters: 5
learning_rate: 0.0001
generation_output_directory: 'generated'

# checkpoint: True
checkpoint_directory: 'checkpoints'
checkpoint_out_directory: 'new_checkpoints'