data: 'train-data'
test-data: 'test-data'
hidden_size: 50
batch_size: 25
sample_iter: 10
num_convolutional_features: 32
max_length: 100
learning_rate: 0.0001
generation_output_directory: 'generated'

# checkpoint: True
# checkpoint_directory: 'checkpoints'
checkpoint_out_directory: 'checkpoints'
