data: 'train-data'
test-data: 'test-data'
hidden_size: 50
batch_size: 10
sample_iter: 100
num_convolutional_features: 8
max_length: 100
learning_rate: 0.00001
generation_output_directory: 'generated'

# checkpoint: True
checkpoint_out_directory: 'checkpoints'
