data: 'train-data'
test-data: 'test-data'
hidden_size: 50
batch_size: 1 
sample_iter: 100
max_length: 100
learning_rate: 0.001
generation_output_directory: 'generated'

checkpoint_directory: 'checkpoints'
checkpoint_out_directory: 'new_checkpoints'
